baseURL = ""
canonifyurls = true
DefaultContentLanguage = "en"
languageCode = "en-us"
relativeURLs = true
title = "Black Cat Apothekare"

[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = -100

[[menu.main]]
  identifier = "shop"
  name = "Shop"
  url = "/shop/"
  weight = -90

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = -90

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = -80

